spring:
  application:
    name: device-management-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/device_management
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: validate
      open-in-view: false

    flyway:
      enabled: true
      locations: classpath:db/migration