spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false

logging:
  level:
    root: INFO
    org.device.management: DEBUG